parameters:
  path:
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
    productId:
      name: productId
      in: path
      required: true
      schema:
        type: string
    variantId:
      name: variantId
      in: path
      required: true
      schema:
        type: string
  header:
    userToken:
      name: user_token
      in: header
      required: true
      description: authorization
      schema:
        type: string
  query:
    productId:
      name: productId
      in: query
      schema:
        type: string
    department:
      name: department
      in: query
      description: The department Men and Women...
      schema:
        type: string
    category:
      name: category
      in: query
      description: The category Jeans,Sweater,etc...
      schema:
        type: string
    order:
      name: order
      in: query
      description: price, -price...
      schema:
        type: string
    range:
      name: range
      in: query
      description: price range '20-30'
      schema:
        type: string
    variantId:
      name: variantId
      in: query
      schema:
        type: string
    query:
      name: query
      requried: true
      in: query
      schema:
        type: string
  requestBody:
    userId:
      name: userId
      type: string
      example: 5caf90b95d51a668344ba1e1
    fullname:
      name: fullname
      example: bob
      description: User full name.
      required: true
      type: string
    email:
      name: email
      example: bob@bob.com
      description: Email to register new account.
      required: true
      type: string
    password:
      name: password
      example: Ab123123
      description: Password for new account.
      type: string
    verifyPassword:
      name: verifyPassword
      example: Ab123123
      description: Verify new password again.
      type: string
    productId:
      name: productId
      example: 5bedf5eec14d7822b39d9d4e
      type: string
    increase:
      name: increase
      example: false
      type: boolean
    decrease:
      name: decrease
      example: true
      type: boolean
  users:
    signin:
      schema:
        type: object
        properties:
          fullname:
            $ref: '#/parameters/requestBody/fullname'
          email:
            $ref: '#/parameters/requestBody/email'
          password:
            $ref: '#/parameters/requestBody/password'
          verifyPassword:
            $ref: '#/parameters/requestBody/verifyPassword'
    login:
      schema:
        type: object
        properties:
          credential:
            requried: true
            type: object
            properties:
              email:
                $ref: '#/parameters/requestBody/email'
              password:
                $ref: '#/parameters/requestBody/password'
    createCart:
      schema:
        type: object
        properties:
          userId:
            $ref: '#/parameters/requestBody/userId'
          productId:
            $ref: '#/parameters/requestBody/productId'
          increase:
            $ref: '#/parameters/requestBody/increase'
          decrease:
            $ref: '#/parameters/requestBody/decrease'
responses:
  users:
    signin:
      201:
        description: user created
        content:
          application/json:
            schema:
              type: object
              example: {
                "message": "user created"
              }
      400:
        description: Bad request
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 400,
                "type": "missing_field",
                "error": {
                  "errors": [
                    {
                      "param": "username",
                      "msg": "username is required"
                    }
                  ]
                }
              }
      409:
        description: Existed user
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 409,
                "type": "invalid_field",
                "error": {
                  "message": "user is existed"
                }
              }
    login:
      201:
        description: user token created
        content:
          application/json:
            schema:
              type: object
              example: {
                "user_token": {
                  "user_id": "5c9d2e70bbb680869617ea63",
                  "user_name": "bob",
                  "token": "Due6daUTre",
                  "expire_in": 2592000
                }
              }
      400:
        description: missing field
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 400,
                "type": "missing_field",
                "error": {
                  "message": "missing username or password"
                }
              }
      403:
        description: Incorrect username or password
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 403,
                "type": "invalid_field",
                "error": {
                  "message": "Incorrect username or password"
                }
              }
    getCart:
      200:
        description: Find cart success
        content:
          application/json:
            schema:
              type: object
              example: {
                "cart": {
                  "_id": "5cafefa23e358c6d7669333b",
                  "items": {
                    "5bedf5eec14d7822b39d9d4e": {
                      "item": {
                        "_id": "5bedf5eec14d7822b39d9d4e",
                        "imagePath": "/uploads/1775300615_1_1_1.jpg",
                        "title": "Perl Knit Swear",
                        "description": "Purl-stitch knit sweater in a combination of textures. Ribbed trim.",
                        "price": 79.99,
                        "color": "Orange",
                        "size": "M,L",
                        "quantity": 5,
                        "department": "Men",
                        "category": "Knitwear"
                      },
                      "qty": 0,
                      "price": 79.99
                    }
                  },
                  "totalQty": 8,
                  "totalPrice": "401.92,",
                  "userId": "5ca266b847c6e01609fe6e21"
                }
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      404:
        description: Find cart fail
    createCart:
      201:
        description: Create cart success
        content:
          application/json:
            schema:
              type: object
              example: {
                "cart": {
                  "_id": "5cafefa23e358c6d7669333b",
                  "items": {
                    "5bedf5eec14d7822b39d9d4e": {
                      "item": {
                        "_id": "5bedf5eec14d7822b39d9d4e",
                        "imagePath": "/uploads/1775300615_1_1_1.jpg",
                        "title": "Perl Knit Swear",
                        "description": "Purl-stitch knit sweater in a combination of textures. Ribbed trim.",
                        "price": 79.99,
                        "color": "Orange",
                        "size": "M,L",
                        "quantity": 5,
                        "department": "Men",
                        "category": "Knitwear"
                      },
                      "qty": 0,
                      "price": 79.99
                    }
                  },
                  "totalQty": 8,
                  "totalPrice": "401.92,",
                  "userId": "5ca266b847c6e01609fe6e21"
                }
              }
      400:
        description: Create cart fail
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
  products:
    getAllProducts:
      200:
        description: Get all products success
        content:
          application/json:
            schema:
              type: object
              example: {
                "products": [
                  {
                    "_id": "5bedf5eec14d7822b39d9d4e",
                    "imagePath": "/uploads/1775300615_1_1_1.jpg",
                    "title": "Perl Knit Swear",
                    "description": "Purl-stitch knit sweater in a combination of textures. Ribbed trim.",
                    "price": 79.99,
                    "color": "Orange",
                    "size": "M,L",
                    "quantity": 5,
                    "department": "Men",
                    "category": "Knitwear"
                  }
                ]
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      404:
        description: Get all products fail
    getProduct:
      200:
        description: Find product success
        content:
          application/json:
            schema:
              type: object
              example: {
                "product": {
                  "_id": "5bedf5eec14d7822b39d9d4e",
                  "imagePath": "/uploads/1775300615_1_1_1.jpg",
                  "title": "Perl Knit Swear",
                  "description": "Purl-stitch knit sweater in a combination of textures. Ribbed trim.",
                  "price": 79.99,
                  "color": "Orange",
                  "size": "M,L",
                  "quantity": 5,
                  "department": "Men",
                  "category": "Knitwear"
                }
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      404:
        description: Not found
  variants:
    getAllVariants:
      200:
        description: Get all variants success
        content:
          application/json:
            schema:
              type: object
              example: {
                "variants": [
                  {
                    "_id": "5feae2f546df702ab96d5e63",
                    "productID": "5bedf3b9c14d7822b39d9d45",
                    "imagePath": "https://static.zara.net/photos///2018/I/0/1/p/5644/641/735/2/w/1920/5644641735_2_5_1.jpg?ts=1540395590656",
                    "color": "Copper",
                    "size": "S,L,XL",
                    "quantity": 12,
                    "__v": 0
                  }
                ]
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      404:
        description: Get all products fail
    getVariant:
      200:
        description: Find variant success
        content:
          application/json:
            schema:
              type: object
              example: {
                "variant": 
                  {
                    "_id": "5feae2f546df702ab96d5e63",
                    "productID": "5bedf3b9c14d7822b39d9d45",
                    "imagePath": "https://static.zara.net/photos///2018/I/0/1/p/5644/641/735/2/w/1920/5644641735_2_5_1.jpg?ts=1540395590656",
                    "color": "Copper",
                    "size": "S,L,XL",
                    "quantity": 12,
                    "__v": 0
                  }
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      404:
        description: Not found
  departments:
    getAllDepartments:
      200:
        description: Get all departments success
        content:
          application/json:
            schema:
              type: object
              example: {
                "departments": [
                  {
                    "_id": "5cb7cd503f467927c8313c3c",
                    "departmentName": "Women",
                    "categories": "Basics,Blazer"
                  }
                ]
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      500:
        description: Get all departments fail
  categories:
    getAllCategories:
      200:
        description: Get all categories success
        content:
          application/json:
            schema:
              type: object
              example: {
                "categories": [
                  {
                    "_id": "5cb7cd503f467927c8313c38",
                    "categoryName": "Blazer"
                  }
                ]
              }
      401:
        description: Authentication fail
        content:
          application/json:
            schema:
              type: object
              example: {
                "status": 401,
                "type": "invalid_field",
                "error": {
                  "message": "Token is not valid"
                }
              }
      500:
        description: Get all categories  fail
  filter:
    200:
      description: Find products success
      content:
        application/json:
          schema:
            type: object
            example: {
              "filter": {
                "department": [
                  "Men"
                ],
                "category": [
                  "Jeans"
                ],
                "title": [
                  "Perl Knit Swear"
                ]
              }
            }
    401:
      description: Authentication fail
      content:
        application/json:
          schema:
            type: object
            example: {
              "status": 401,
              "type": "invalid_field",
              "error": {
                "message": "Token is not valid"
              }
            }
    500:
      description: Get all categories  fail